# Generated by Django 4.2.5 on 2023-09-14 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitfood', '0003_reciperating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='total_ratings',
        ),
        migrations.DeleteModel(
            name='RecipeRating',
        ),
    ]
