# Generated by Django 4.2.5 on 2023-09-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitfood', '0009_alter_comment_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='describe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
