# Generated by Django 4.2.5 on 2023-09-13 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitmanage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='specialization',
            new_name='specialist',
        ),
    ]
