# Generated by Django 4.2.5 on 2023-09-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitmanage', '0002_rename_specialization_trainer_specialist'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='price',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='type_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
