# Generated by Django 4.2.5 on 2023-09-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitmanage', '0003_type_price_type_type_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='price',
            field=models.FloatField(),
        ),
    ]
