# Generated by Django 4.2.5 on 2023-09-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitmanage', '0005_alter_type_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmember',
            name='address',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='specialist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
