# Generated by Django 4.2.5 on 2023-09-21 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitmanage', '0007_type_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
