# Generated by Django 4.2.5 on 2023-09-15 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitform', '0002_exercise_workoutcategory_workoutprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fitform.workoutcategory'),
        ),
    ]
