# Generated by Django 4.2.5 on 2023-09-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitform', '0003_exercise_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exercise_images'),
        ),
        migrations.DeleteModel(
            name='WorkoutProgram',
        ),
    ]
