# Generated by Django 4.2.5 on 2023-09-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitform', '0004_workoutcategory_image_alter_exercise_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
