# Generated by Django 4.2.5 on 2023-09-15 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitform', '0005_helppage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelpPage',
        ),
    ]
