# Generated by Django 4.2.5 on 2023-09-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitform', '0006_delete_helppage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercise_images')),
                ('description', models.TextField()),
            ],
        ),
    ]
